// Code generated by Slice Machine. DO NOT EDIT.

import GroupOfLinks from './GroupOfLinks';
import Hero from './Hero';
import Image from './Image';
import ImageCards from './ImageCards';
import Quote from './Quote';
import Text from './Text';
import TextWithImage from './TextWithImage';

export {
	GroupOfLinks,
	Hero,
	Image,
	ImageCards,
	Quote,
	Text,
	TextWithImage,
};

export const components = {
	group_of_links: GroupOfLinks,
	hero: Hero,
	image: Image,
	image_cards: ImageCards,
	quote: Quote,
	text: Text,
	text_with_image: TextWithImage,
};
